### PR TITLE
Make laserPointer more visible

### PR DESCRIPTION
**Pull request by alexvornoffice**
Increase color from 0.1 to 0.35

### CODE REVIEW

**Comment by zbot473** [comment]
Have you tested this?

**Comment by alexvornoffice** [comment]
yes

**Comment by zbot473** [comment]
cool

**Comment by zbot473** [comment]
sorry i closed it

**Comment by zbot473** [comment]
Can you test if you get the new version ?
it should happen in ~10min

**Comment by zbot473** [comment]
@alexvornoffice do you get a new version notification?

**Pull request merged**
