### PR TITLE
A little fix

### PR DESCRIPTION
**Pull request by alexvornoffice**
1: replaced menu variable now it works
2. increased the the default value of "smoothlevel" from 3 to 6 so the cheat will look less suspicions
3. added app.js latest file, so why not to have it?

### CODE REVIEW

**Comment by FallingBoi** [comment]
So, u repair the problem? The hacks doesnt works, only the transparency, aimbot, autoloot, etc. doesnt works, yesterday it was working good, but wtf boi, today have no zoom and some ppl are saying it crashes.

**Comment by alexvornoffice** [comment]
yes, now it works, zoom and aim, not tested everything but U can play :D

**Comment by merelymemeulous** [comment]
yeah

**Comment by zbot473** [comment]
We don't really need the app js file

**Comment by ThanksMrSotarks** [comment]
see the thing is that you should always test it first before making commits because B O I this shit crash
image
@alexvornoffice @zbot473

**Comment by alexvornoffice** [comment]
> see the thing is that you should always test it first before making commits because B O I this shit crash
> image
> @alexvornoffice @zbot473

for me it works... :|

**Comment by alexvornoffice** [comment]
> There aren't any references.
I know it, but for future to compare the files so we can know what changed and where to look for new "things", so when new version appear just diff the files, the new one from the site and the old one from the plugin...

**Comment by zbot473** [comment]
just download it

**Comment by ThanksMrSotarks** [comment]
we have a fix thread already, just look over it and check for the doc file

**Pull request merged**
