### PR TITLE
Patch fix

### PR DESCRIPTION
**Pull request by zbot473**
I can't test but maybe it'll work

### CODE REVIEW

**Comment by ThanksMrSotarks** [comment]
changed the file myself and tested it, fully disables the cheat.

**Comment by ThanksMrSotarks** [comment]
think it'll have to do something with the init file

**Comment by zbot473** [comment]
@thanksmrsotarks check the console

**Comment by cj2kplays** [comment]
hey

**Comment by cj2kplays** [comment]
do you know how to fix the hack?

**Pull request merged**
